# Site settings
title:       Roman Minkin
email:       minkinroman@gmail.com
author:      Roman Minkin
description: "Roman Minkin's personal website and blog."
baseurl:     ""
url:         "http://www.minkin.me"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: minkin

# Social icons
github_username: RomanMinkin
bitbucket_username:
stackoverflow_id:
twitter_username: RomanMinkin
google_plus_id:
linkedin_username: romanminkin
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: ''
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap